# run the same job on 2 CI machines in parallel
# https://docs.microsoft.com/en-us/vsts/pipelines/process/phases
jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: npm ci
        displayName: 'Install NPM dependencies'
      - script: npm run cy:verify
        displayName: 'Cypress verify'
      - script: npm run cy:percy
        displayName: 'Run Percy Test'
        env:
          PERCY_TOKEN: $(PERCY_TOKEN)
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'testResults/**test-*.xml'
